on:
  pull_request:

name: lint-changed-files.yaml

permissions: read-all

jobs:
  lint-changed-files:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Remove renv and .Rprofile
        run: |
          if [ -d "renv" ]; then
          rm -rf renv
          fi
          if [ -f ".Rprofile" ]; then
            rm -f .Rprofile
          fi

      - uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${hashFiles('DESCRIPTION')}}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install R packages
        run: Rscript -e "install.packages(c('lintr', 'gh'), repos = 'https://cloud.r-project.org/')"

      - name: Add lintr options
        run: |
          cat('\noptions(lintr.linter_file = ".lintr")\n', file = "~/.Rprofile", append = TRUE)
        shell: Rscript {0}

      - name: Extract and lint files changed by this PR
        run: |
          files <- gh::gh("GET https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files")
          changed.files <- sapply(files, function(x) x$filename)
          r.files <- changed.files[grepl("\\.(R|Rmd|qmd)$", changed.files, ignore.case = TRUE)]
          lapply(r.files, lintr::lint)
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
